POST http://localhost:3003/api/blogs
Content-Type: application/json
  
  {
    "title": "Testing my blog",
    "author": "chalestone",
    "url": "www.globalactions.com",
    "likes": 6
  }
### 
POST http://localhost:3003/api/blogs
Content-Type: application/json
  
  {
    "title": "Testing my Mongoose",
    "author": "Michael Chan",
    "url": "www.globalactions.com",
    "likes": 6,
    "userId":"66716a2c7f33c864cce5e0ad"
  }

###  
POST http://localhost:3003/api/blogs
Content-Type: application/json
  
  {
    "title": "Testing my luchos posts",
    "author": "Luciano Ramello",
    "url": "www.luchosr.com",
    "likes": 6,
    "userId":"667198ce7e668854c20418c4"
  }
###

POST http://localhost:3003/api/blogs
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1Y2hvc3IiLCJpZCI6IjY2NzE5OGNlN2U2Njg4NTRjMjA0MThjNCIsImlhdCI6MTcxOTIzNjI0NywiZXhwIjoxNzE5MjM5ODQ3fQ.7_g7KP9YynX4WjRfS0T6D-lMQkejs1Bwv35MhkeR0-Q
{
    "title": "User extractor post",
    "author": "Luciano Ramello",
    "url": "www.luchosr.com",
    "likes": 6,
    "userId":"667198ce7e668854c20418c4"
  }

###
DELETE http://localhost:3003/api/blogs/6673ed2b2b82f99ec7cb0484
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1Y2hvc3IiLCJpZCI6IjY2NzE5OGNlN2U2Njg4NTRjMjA0MThjNCIsImlhdCI6MTcxODg3NDQ2MywiZXhwIjoxNzE4ODc4MDYzfQ.kMlMSo8RpatbL-NdZ7ylvnlZv6yYOE7W7GHrR2FRTAc